### ISSUE TITLE
ImageTable.load_files does not work

### ISSUE THREAD

**Issue by danielecazzari** [sassoftware/python-dlpy#134]
I run Viya 3.4 and I am facing some issue with ImageTable.load_files function on version 1.0.2
Version 1.0.1 works fine.

I use ImageTable.load_files with the following parameter to load images stored in 2 subdirectory under modelPath+'images'
my_images = ImageTable.load_files(conn, path=modelPath+'images',casout=dict(name='my_images',caslib='Happy'))

The function does not return any error after execution but a subsequent command:
   s.tableinfo()
return
   NOTE: No tables are available in caslib Happy of Cloud Analytic Services.

Then after this command the caslib='Happy' is made invalid and no more accessible.

Thanks a lot for the support.

**Comment by sasxianhu** [comment]
Can you try to use the latest version by git clone? 
Is the happy caslib valid for you to write? 
the path should be accessible to your CAS server.

**Comment by ethem-kinginthenorth** [comment]
I am assuming the caslib happy's path and the path that you passed are in the same location, right?

**Comment by danielecazzari** [comment]
modelPath variable is the path of caslib happy, so yes the pictures that I'm trying to load are in the same location under a subdirectory called images.
My user has all the permission to the modelPath directory, moreover the same script with version 1.0.1 works and with 1.0.2 not (without any other changes).

**Comment by ethem-kinginthenorth** [comment]
I believe I know what is happening. Dlpy aims at hiding caslib so that a user does not need to worry about it. In your case, you are handling it and it is kind of changing things. I will investigate your scenario in detail. I think when you create the caslib, I am assuming you are making it active, then load the files, and the call drop the caslib and your tables are gone.

That said, you can do two things as a work around; 1) pass caslib parameter while doing the call and pass the relative path. 2) do not create the caslib beforehand and pass the full path and then do the call - a temp caslib would be created for you and the table will be living in the active caslib

**Comment by danielecazzari** [comment]
Yes correct I'm creating the caslib and make it active. About your suggestion I'm not sure about step 1 since I believe to do already what you are suggesting:
my_images = ImageTable.load_files(conn, path=modelPath+'images',casout=dict(name='my_images',caslib='Happy'))
The ImageTable.load_files includes the active caslib named Happy (caslib='Happy') and the caslib modelPath. Did I miss something? 
Anyhow the problem is that the above command works with version 1.0.1 (that I'm currently using) and does not work with 1.0.2. Should I use the function in a different way on 1.0.2 (e.g. is mandatory to do step 2 in this new version)?

**Comment by ethem-kinginthenorth** [comment]
@danielecazzari could you please download the latest copy from git (e.g., git clone) and try against that version. I believe the current version (not the latest release) would resolve this issue. Thanks

**Comment by danielecazzari** [comment]
Yes with the 1.0.3-dev the issue is fixed. Thanks a lot
