### ISSUE TITLE
ImageTable issue with backslash-based paths

### ISSUE THREAD

**Issue by kybowm** [sassoftware/python-dlpy#208]
![Capture](https://user-images.githubusercontent.com/51750376/65057111-154ccd80-d940-11e9-8057-ccab250d6ffc.PNG)
The ImageTable.load_files method gets image name by parsing path for a forward slash. If a user submits a backslash-based path, the images will load correctly, but _filename_0 will be an empty string for all images.

**Comment by ethem-kinginthenorth** [comment]
Yes, it looks like the legacy code does not pay attention to the os of the server. as the load_files calls an action that requires the images are accessible from the cas server. the image path has to be in the same format as the server's os. therefore, when we are creating the filename, we can use the separator rather than a fixed one. great catch. thanks

**Comment by ethem-kinginthenorth** [comment]
Thanks @kybowm for finding this issue, I have a fix and about to push.
