### ISSUE TITLE
ERROR: Parameter 'dataspecs[0].lossscalefactor' is not recognized.

### ISSUE THREAD

**Issue by sasbsg** [sassoftware/python-dlpy#213]
When I define a data_specs and pass it into a Tiny_YoloV2 model, I get an error.

from dlpy.model import DataSpec
data_specs = [DataSpec(type_='IMAGE',
                      layer='Input1',
                      data=inputVars,
                      loss_scale_factor=1),
             DataSpec(type_='OBJECTDETECTION',
                     layer='Detection1',
                     loss_scale_factor=1,
                     data=targets)]
from dlpy.model import Gpu
gpu= Gpu(devices=[0,1])
yolo_model.fit(data={"name":"trainset",
                    "where":"_nObjects_ > 0"},
              optimizer=optimizer,
              data_specs=data_specs,
              n_threads=1,
              record_seed = 13309,
              force_equal_padding=True,
              gpu=gpu
              )

NOTE: Training from scratch.
ERROR: Parameter 'dataspecs[0].lossscalefactor' is not recognized.
ERROR: Expecting one of the following as a subparameter to 'dataspecs[0]': type, layer, data, nominals, numericNominalParms, name, layerName, nominal, numnomParms.
ERROR: The action stopped due to errors.

Am I doing something wrong?

**Comment by sasxianhu** [comment]
Do you use VDMML 8.3 or 8.4?

The latest DLPy only supports 8.4.

Best,
XQ

On Sep 21, 2019, at 9:45 PM, sasbsg <notifications@github.com<mailto:notifications@github.com>> wrote:


EXTERNAL

When I define a data_specs and pass it into a Tiny_YoloV2 model, I get an error.

from dlpy.model import DataSpec
data_specs = [DataSpec(type_='IMAGE',
layer='Input1',
data=inputVars,
loss_scale_factor=1),
DataSpec(type_='OBJECTDETECTION',
layer='Detection1',
loss_scale_factor=1,
data=targets)]
from dlpy.model import Gpu
gpu= Gpu(devices=[0,1])
yolo_model.fit(data={"name":"trainset",
"where":"nObjects > 0"},
optimizer=optimizer,
data_specs=data_specs,
n_threads=1,
record_seed = 13309,
force_equal_padding=True,
gpu=gpu
)

NOTE: Training from scratch.
ERROR: Parameter 'dataspecs[0].lossscalefactor' is not recognized.
ERROR: Expecting one of the following as a subparameter to 'dataspecs[0]': type, layer, data, nominals, numericNominalParms, name, layerName, nominal, numnomParms.
ERROR: The action stopped due to errors.

Am I doing something wrong?

**Comment by sasbsg** [comment]
I'm running a SMP CAS in a Docker container.  My /var/log/sas/viya/cas/default/cas*.log file includes this:
SAS Cloud Analytic Services Version V.03.04M0P07122018
Is that the best way to look that up?

**Comment by sasxianhu** [comment]
It is VDMML 8.3. You could use DLPy 1.0 not 1.1.

Best,
XQ

On Sep 21, 2019, at 10:45 PM, sasbsg <notifications@github.com<mailto:notifications@github.com>> wrote:


EXTERNAL

I'm running a SMP CAS in a Docker container. My /var/log/sas/viya/cas/default/cas*.log file includes this:
SAS Cloud Analytic Services Version V.03.04M0P07122018
Is that the best way to look that up?

**Comment by ethem-kinginthenorth** [comment]
@sasbsg we have a list on the main page (readme) indicating vdmml and sas viya versions. Would you please try the latest dlpy version 1.0.2? thanks
