### ISSUE TITLE
ONNX model import fails to load weights

### ISSUE THREAD

**Issue by smlindauer** [sassoftware/python-dlpy#265]
I have an ONNX model (attached with weights), which I load onto CAS via:
```python
onnxModel = onnx.load(path)
newModel = Model.from_onnx_model(conn, onnxModel, output_model_table='mnist')
```
This produces the expected output of:
```bash
NOTE: Successfully created connection to CAS server. <**Removed**>
NOTE: Successfully written weights file as <**Removed**>mnist_weights.onnxmodel.h5
NOTE: Model table is attached successfully!
NOTE: Model is named to "mnist" according to the model name in the table.
NOTE: Successfully imported ONNX model.
```
However, after uploading the weights file to a server-side location and running the following:
```python
newModel.load_weights(weightsPath)
```
I get the following output:
```bash
NOTE: no dataspec(s) provided - creating image classification model.
NOTE: Model weights attached successfully!
ERROR: The specified Keras model file was not found.
ERROR: The action stopped due to errors.
```
I also attempted to run the same process with the deeplearn actionset directly with either of the formattype options (CAFFE and KERAS):
```python
conn.deeplearn.dlimportmodelweights(modeltable='mnist', modelweights='mnist_weights', weightfilepath=localWeightsPath)
```
Each of these function calls returned the same error of not finding the model file.

When attempting to load the weights, am I failing to point the weights to the correct CAS table, which is why it can't find the model file? And is the ONNX model being converted into a Keras model by the from_onnx_model, which is why its searching for a Keras model instead of an ONNX model? 

[mnistONNXModelAndWeights.zip](https://github.com/sassoftware/python-dlpy/files/4086949/mnistONNXModelAndWeights.zip)

**Comment by eusdougc** [comment]
@smlindauer - The error you are reporting indicates that your Viya server cannot find the file you specified with your variable weightsPath.  Can you confirm that weightsPath does indeed specify a valid file that is visible to the server?  Also, you (as a Viya user) need to have permission to access the file.  This would be important if you assumed super user privilege to copy the file to a directory that only root normally has access to (for example).  Your Viya session could not read such a file.

To answer this question: 

> When attempting to load the weights, am I failing to point the weights to the correct CAS table, which is why it can't find the model file? And is the ONNX model being converted into a Keras model by the from_onnx_model, which is why its searching for a Keras model instead of an ONNX model?

The issue is that the Viya server cannot find the model file as I stated above.  The model weights that are associated with ONNX/CAFFE/KERAS models are written to an intermediate HDF5 file so that they can be read by the deep learning actions.  The ONNX conversion routines call the KERAS routines because the format of the HDF5 file is very similar - that is why you are seeing that particular error message.  We need to clean that up so it is not so misleading.

**Comment by smlindauer** [comment]
@eusdougc - As you stated, it looks like the Viya server did not in fact have access to the file. (It now works with the file accessible to the server.) 

I had been trying to place the weights file on a file share server instead of uploading directly to the Viya server in order to avoid needing to SFTP. Is there anyway to run the `load_weights` function such that it calls the local file that is written by the `from_onnx_model` function instead of pointing to a server-side location?

**Comment by eusdougc** [comment]
@smlindauer - It depends on your client/server configuration.  If your client and server are running on the same computer, then what want is very straightforward (and no need to copy files).  If your client and server are running on separate computers, then then you must copy the file from the client to the server unless there is some sort of common file system.  For example, there are some directories that are mounted in such a way that they are visible to my Windows desktop and the Linux boxes where we run our Viya servers.  In this case, I simply have to copy the intermediate file created by my Windows client over to one of these common directories.  Of course I have to make sure I qualify the path correctly on the server side when I go to load the weights.
