### ISSUE TITLE
MPP and some of these workers have GPUs

### ISSUE THREAD

**Issue by staceychan** [sassoftware/python-dlpy#354]
Hi Expert,

We have a MPP clusters like this
Primary Controller 
Backup Controller
Microservice 1
Microservice 2
Microservice 3
Worker1 (1 GPU)
Worker2 (1 GPU)
Worker3 (CPU)
Worker4 (CPU)
Wroker5 (CPU)

Is there any way we can run our trianing process with both GPU and CPU? (this is our first choice)
or maybe just run on the two workers with GPU

Thanks in advance! :)

**Comment by staceychan** [comment]
We do some test and the result as below
When we use gpu=1 the output seems it use GPU but the first batch takes much time than CPU mode(second figure).
Is it because we use both GPUs and CPUs?
Is there any way we can just run on the GPU devices?
![image](https://user-images.githubusercontent.com/35584966/106429492-7ded0980-64a5-11eb-9dd2-e6d99d65517c.png)
![image](https://user-images.githubusercontent.com/35584966/106429612-a117b900-64a5-11eb-82c5-9985411504be.png)

Also there are some question 
1. ResNet model would fail
![image](https://user-images.githubusercontent.com/35584966/106432279-76c7fa80-64a9-11eb-935f-01c7ade2df19.png)
2. Running on the MPP cluster with two GPUs are more slower than the SMP with one GPU (Same model, same GPU)
3. 
![image](https://user-images.githubusercontent.com/35584966/106432667-feae0480-64a9-11eb-9fc1-68e46c329825.png)

We appreciate for any suggestion. :)

**Comment by eusdougc** [comment]
@staceychan - here are some answers to your questions.

1) Is there any way we can run our trianing process with both GPU and CPU? (this is our first choice) - this is what you get when you have a mixed Viya deployment (i.e. some workers with GPUs, other workers with CPUs)

2) or maybe just run on the two workers with GPU - the simplest way to do this is to start another Viya server that just uses the two nodes with GPUs as the workers.  You cannot easily get this kind of behavior with a mixed Viya deployment.

3) ResNet model would fail - this can happen for certain data sets.  For example, let's say you took a single image and duplicated it N times to create your data set.  The batch statistics for this data set would be the mean of the initial image, but the standard deviation for this data set would be 0, and this would trigger the error you see.  Is there something unusual about the data set you are working with?

4) Running on the MPP cluster with two GPUs are more slower than the SMP with one GPU (Same model, same GPU) - I believe you are comparing an MPP server where some of the workers have GPUs and some have CPUs to either an SMP server or an MPP server with only 1 worker with a GPU.  The mixed MPP server will be slower because the workers with GPUs have to wait for the workers with CPUs before they can process the next minibatch.  The workers with CPUs will be considerably slower than those with GPUs, and will slow the overall processing down.  If you want a fair comparison, try starting an MPP server using only the worker nodes with GPUs.

**Comment by dxq77dxq** [comment]
@staceychan 
The comments from @eusdougc are pretty thorough and hope they can address your questions or concerns. Just add one more note for the time diff between MPP and SMP - even when all MPP clusters are with GPU, sometimes MPP mode is still slower. Simply speaking, for MPP mode data need to be sent to multiple workers, and the controller need to gather statistics / output from different workers. While there're fewer observations on each worker while shorten the processing time, the time needed for data transfer could be longer. That's why when the sample size is not that huge, SMP is sometimes preferred.

**Comment by staceychan** [comment]
Hi both,

Thanks for your clear explanation. This really help us to clarify the problem.

First, for the resnet issue, we use the same dataset as LeNet5 and VGG16 (mnist).
And we change the dataset to Cifar10, we encounter the same issue.

Maybe I should explain why we need to know the details of GPU on MPP.
Our customer wants to take advantage of the GPUs but there are only 2 of 14 workers have GPU.
So we have to adopt GPU and let GPU benefit their works.
  
Here is my testing performance on our AWS machine

![image](https://user-images.githubusercontent.com/35584966/106588039-4a81ac00-6585-11eb-83c4-2f30b6e6e47d.png)
Note: 2/5 means 2 of 5 workers have GPU
Note: We perform less workers by shutdown that machine

It seems we can get the best performance if only use those two GPU workers.
So we are trying to use just these 2 workers when connect to CAS (without shutdown the other workers).
The code as below
s = CAS("10.249.x.xxx", 5570, "user", "passwd",nworkers=2)

When nworkers=2 we got the performance we want(only 2 GPU workers are used). 
But there are still some concerns.
Does it always means using the first two workers? 
Or how can we get the rule of worker selection? 

Again, it's really helpful to get your opinion and knowledge.
Thanks a lot and hope everything goes well! :)

Best,
Stacey

**Comment by eusdougc** [comment]
@staceychan - the ResNet problem is odd, although I can see a scenario where it might happen for the MNIST data set.  The original MNIST data is single-channel only.  If you use the convenience functions we provide to build ResNet models, the assumption is that the input images consist of 3 channels.  When the data is read in it might be the one valid channel and some constant value for the other two.  That would cause the problem you are seeing.  I haven't worked with the CIFAR10 data, but if it is single-channel as well, that could explain your problem.

Regarding your questions about the MPP cluster

_When nworkers=2 we got the performance we want(only 2 GPU workers are used).
But there are still some concerns.
Does it always means using the first two workers?
Or how can we get the rule of worker selection?_

Selection of worker nodes is beyond the control of DLPy.  This occurs when you set up your Viya server.  We can't help you directly with that.

**Comment by staceychan** [comment]
Hi Doug,

Thanks for your explanation.
I'm going to close this issue
Really appreciate it. :)

Best,
Stacey
