### ISSUE TITLE
Model.from_keras_model throws error "Model layer name not found in Keras definition."

### ISSUE THREAD

**Issue by TheodorGosden** [sassoftware/python-dlpy#45]
I'm trying to import a Keras model via dlpy, but i'm getting an error I just can't seem to get past!

My error is when i'm trying to load in the weights. Here's my code:

#import packages and connect to server
import swat
import pandas as pd
from dlpy import Model, Sequential
from dlpy.model import *
sess = swat.CAS('rpcger01075.exnet.sas.com', 5570, username='sasdemo', password='Orion123')

#read in dataset and create table - if there's a way to create an empty table via SWAT please show me
churn_df = pd.read_csv('C:\\Users\\sdktgo\\OneDrive - SAS\\Code\\Data from Kaggle\\bank churn\\Churn_Modelling.csv')
churn_df.head()

pd.set_option('display.float_format', lambda x: '%.2f' % x)

#upload table to server
out=sess.upload(churn_df,casout=dict(name='Simple_CNN',caslib='casuser'))

#make model
model1 = Sequential(sess, model_table = 'Simple_CNN')
#import weights - fails
model1.load_weights_from_keras('/media/my_model.h5', labels=False)
#output from loading weights:
#note: Model weights attached successfully!
#error: Model layer name not found in Keras definition.
#error: The action stopped due to errors.

Here's the packages I currently use to run in an anaconda env.
Highlight: i'm using keras 2.1.6 as you can se.
absl-py==0.6.1
alabaster==0.7.11
asn1crypto==0.24.0
astor==0.7.1
astroid==2.0.4
Babel==2.6.0
backcall==0.1.0
bleach==2.1.4
certifi==2018.8.24
cffi==1.11.5
chardet==3.0.4
cloudpickle==0.5.5
colorama==0.3.9
cryptography==2.3.1
cycler==0.10.0
decorator==4.3.0
docutils==0.14
entrypoints==0.2.3
gast==0.2.0
graphviz==0.8.4
grpcio==1.16.1
h5py==2.8.0
html5lib==1.0.1
idna==2.7
imagesize==1.1.0
ipykernel==4.10.0
ipython==6.5.0
ipython-genutils==0.2.0
isort==4.3.4
jedi==0.12.1
Jinja2==2.10
jsonschema==2.6.0
jupyter-client==5.2.3
jupyter-core==4.4.0
Keras==2.1.6
Keras-Applications==1.0.6
Keras-Preprocessing==1.0.5
keyring==13.2.1
kiwisolver==1.0.1
lazy-object-proxy==1.3.1
Markdown==3.0.1
MarkupSafe==1.0
matplotlib==3.0.0
mccabe==0.6.1
mistune==0.8.3
mkl-fft==1.0.6
mkl-random==1.0.1
nbconvert==5.3.1
nbformat==4.4.0
numpy==1.15.2
numpydoc==0.8.0
olefile==0.46
packaging==17.1
pandas==0.23.4
pandocfilters==1.4.2
parso==0.3.1
pickleshare==0.7.4
Pillow==5.2.0
prompt-toolkit==1.0.15
protobuf==3.6.1
psutil==5.4.7
pycodestyle==2.4.0
pycparser==2.19
pyflakes==2.0.0
Pygments==2.2.0
pylint==2.1.1
pyOpenSSL==18.0.0
pyparsing==2.2.1
PySocks==1.6.8
python-dateutil==2.7.3
pytz==2018.5
pywin32==223
PyYAML==3.13
pyzmq==17.1.2
QtAwesome==0.4.4
qtconsole==4.4.1
QtPy==1.5.0
requests==2.19.1
rope==0.11.0
sas-dlpy==1.0.0
scipy==1.1.0
simplegeneric==0.8.1
six==1.11.0
snowballstemmer==1.2.1
Sphinx==1.7.9
sphinxcontrib-websupport==1.1.0
spyder==3.3.1
spyder-kernels==0.2.6
swat==1.5.0
tensorboard==1.12.0
tensorflow==1.12.0
termcolor==1.1.0
testpath==0.3.1
tornado==5.1.1
traitlets==4.3.2
typed-ast==1.1.0
urllib3==1.23
wcwidth==0.1.7
webencodings==0.5.1
Werkzeug==0.14.1
win-inet-pton==1.0.1
win-unicode-console==0.5
wincertstore==0.2
wrapt==1.10.11

**Comment by yg2288** [comment]
The h5 file should be generated from `Model.from_keras_model` to be compatible for loading.  See this [example](https://github.com/sassoftware/python-dlpy/blob/master/examples/Example4-KerasModelConversion.ipynb), and specify `include_weights=True`

**Comment by TheodorGosden** [comment]
So it's not possible to build, train and export a model soley in Keras and then import the models weights and layers into DLPy?

Is this something that's planned on being developed? Because I think a customer would be quite disappointed to find out, that all the compute power they spent on training a model can't be moved over and deployed in SAS. As far as I could tell in the h5 file from keras, all the information regarding the layers, was there. I had something like the following in my keras file:

`{"class_name": "Sequential", "config": {"layers": [{"class_name": "Dense", "config": {"dtype": "float32", "units": 512, "batch_input_shape": [null, 784], "activity_regularizer": null, "kernel_constraint": null, "kernel_regularizer": null, "bias_constraint": null, "name": "dense_1", "bias_initializer": {"class_name": "Zeros", "config": {}}, "kernel_initializer": {"class_name": "VarianceScaling", "config": {"mode": "fan_avg", "scale": 1.0, "distribution": "uniform", "seed": null}}, "use_bias": true, "activation": "relu", "bias_regularizer": null, "trainable": true}}, {"class_name": "Dropout", "config": {"rate": 0.2, "noise_shape": null, "trainable": true, "name": "dropout_1", "seed": null}}, {"class_name": "Dense", "config": {"bias_constraint": null, "use_bias": true, "activity_regularizer": null, "trainable": true, "kernel_regularizer": null, "name": "dense_2", "units": 512, "kernel_initializer": {"class_name": "VarianceScaling", "config": {"mode": "fan_avg", "scale": 1.0, "distribution": "uniform", "seed": null}}, "bias_regularizer": null, "activation": "relu", "bias_initializer": {"class_name": "Zeros", "config": {}}, "kernel_constraint": null}}, {"class_name": "Dropout", "config": {"rate": 0.2, "noise_shape": null, "trainable": true, "name": "dropout_2", "seed": null}}, {"class_name": "Dense", "config": {"bias_constraint": null, "use_bias": true, "activity_regularizer": null, "trainable": true, "kernel_regularizer": null, "name": "dense_3", "units": 10, "kernel_initializer": {"class_name": "VarianceScaling", "config": {"mode": "fan_avg", "scale": 1.0, "distribution": "uniform", "seed": null}}, "bias_regularizer": null, "activation": "softmax", "bias_initializer": {"class_name": "Zeros", "config": {}}, "kernel_constraint": null}}], "name": "sequential_1"}}`

and 

`{"sample_weight_mode": null, "loss": "categorical_crossentropy", "loss_weights": null, "optimizer_config": {"class_name": "RMSprop", "config": {"lr": 0.0010000000474974513, "epsilon": 1e-07, "rho": 0.8999999761581421, "decay": 0.0}}, "metrics": ["accuracy"]}`

**Comment by sasxianhu** [comment]
Of course, it is supported. Alex suggested to check that example, which import the Keras model directly. load_weights_from_keras can only import the weights but you need define your model first. Model.from_keras_model imports both the keras model and its weights.

**Comment by eusdougc** [comment]
To expand upon what @sasxianhu said, we do support importing a model you build in Keras.  However, you have to define that model in DLPy so that the layers/weights can be imported correctly.  Your model definition is this:

model1 = Sequential(sess, model_table = 'Simple_CNN')

That is basically a definition of an empty model object.  You need to include the layer definition(s).  Something like this:

model1.add(Conv2D(32, kernel_size=(5, 5), strides=(1, 1),
                 activation='relu',padding='same',
                 input_shape=(28,28,1)))
model1.add(MaxPooling2D(pool_size=(2, 2), padding='same', strides=(2, 2)))
model1.add(Conv2D(64, (5, 5), padding='same', activation='relu'))
model1.add(MaxPooling2D(pool_size=(2, 2), padding='same'))
model1.add(Flatten())
model1.add(Dense(1000, activation='relu'))
model1.add(Dense(10, activation='softmax'))

Note that the layers (names, parameters, etc.) you define in DLPy must match **exactly** with your Keras model.  Deviations will cause the model import to fail, or will give poor performance when using the model for inference.

**Comment by ethem-kinginthenorth** [comment]
For the documentation, you can also check the source code (line 236 in model.py). Functions in the source code has documentation - if we missed to add it into the doc html.

**Comment by eusdougc** [comment]
@TheodorGosden - what picture are you referring to here: "As far as I can see the params don't match exactly (see pic), but I have no clue why they are off with +-512 and 10?"

**Comment by TheodorGosden** [comment]
Sorry forgot to attach the picture! @eusdougc 
![image](https://user-images.githubusercontent.com/19152803/49020943-de7bb000-f191-11e8-8e37-c1630876d7ac.png)

**Comment by TheodorGosden** [comment]
@ethem-kinginthenorth Thank you! It's failing when importing weights via `Model.from_keras_model`
This is my code (focus on the last bit, just wanted to give you guys the full picture, if you want to replicate)

'''Trains a simple deep NN on the MNIST dataset.
Gets to 98.40% test accuracy after 20 epochs
(there is *a lot* of margin for parameter tuning).
2 seconds per epoch on a K520 GPU.
'''

from __future__ import print_function

import keras
from keras.datasets import mnist
from keras.models import Sequential
from keras.layers import Dense, Dropout, Conv2D, MaxPooling2D, Flatten
from keras.optimizers import RMSprop


batch_size = 128
num_classes = 10
epochs = 10

##the data, shuffled and split between train and test sets
(x_train, y_train), (x_test, y_test) = mnist.load_data()

x_train = x_train.reshape(60000, 784)
x_test = x_test.reshape(10000, 784)
x_train = x_train.astype('float32')
x_test = x_test.astype('float32')
x_train /= 255
x_test /= 255
print(x_train.shape[0], 'train samples')
print(x_test.shape[0], 'test samples')

##convert class vectors to binary class matrices
y_train = keras.utils.to_categorical(y_train, num_classes)
y_test = keras.utils.to_categorical(y_test, num_classes)


model = Sequential()
model.add(Dense(512, activation='relu', input_shape=(784,)))
model.add(Dropout(0.2))
model.add(Dense(512, activation='relu'))
model.add(Dropout(0.2))
model.add(Dense(num_classes, activation='softmax'))

model.summary()

model.compile(loss='categorical_crossentropy',
              optimizer=RMSprop(),
              metrics=['accuracy'])

history = model.fit(x_train, y_train,
                    batch_size=batch_size,
                    epochs=epochs,
                    verbose=1,
                    validation_data=(x_test, y_test))
score = model.evaluate(x_test, y_test, verbose=0)
print('Test loss:', score[0])
print('Test accuracy:', score[1])


from dlpy import Model
import swat
sess = swat.CAS('rpcger01165.exnet.sas.com', 5570, username='sasdemo', password='Orion123')

model1 = Model.from_keras_model(conn=sess, 
                                keras_model=model,
                                output_model_table='converted_keras_model',
                                include_weights=True,
                                input_weights_file='/media/my_model_2.h5')

**I'm getting the following error: **
model1 = Model.from_keras_model(conn=sess, keras_model=model, output_model_table='converted_keras_model', include_weights=True, input_weights_file='/media/my_model_2.h5')
Traceback (most recent call last):

  File "<ipython-input-96-e5ba344563dd>", line 1, in <module>
    model1 = Model.from_keras_model(conn=sess, keras_model=model, output_model_table='converted_keras_model', include_weights=True, input_weights_file='/media/my_model_2.h5')

  File "C:\Users\sdktgo\AppData\Local\conda\conda\envs\tensorflowkeras2\lib\site-packages\dlpy\model.py", line 276, in from_keras_model
    output_code = keras_to_sas(model=keras_model, model_name=model_name)

  File "C:\Users\sdktgo\AppData\Local\conda\conda\envs\tensorflowkeras2\lib\site-packages\dlpy\model_conversion\sas_keras_parse.py", line 75, in keras_to_sas
    sas_code = keras_input_layer(layer, model_name, False)

  File "C:\Users\sdktgo\AppData\Local\conda\conda\envs\tensorflowkeras2\lib\site-packages\dlpy\model_conversion\sas_keras_parse.py", line 372, in keras_input_layer
    dummy, H, W, C = config['batch_input_shape']

ValueError: not enough values to unpack (expected 4, got 2)

**Comment by eusdougc** [comment]
@TheodorGosden: my brain must be working a little slowly after the long holiday weekend.  In my initial response I should have said that you need to include the **Keras** model definition and then call model1.from_keras_model().  My apologies.  That said, the code you just posted should work, although I see that you appear to be flattening the input:

x_train = x_train.reshape(60000, 784)
x_test = x_test.reshape(10000, 784)

Are x_train and x_test 4-D tensors with dimensions (60000, 28, 28, 1) and (10000, 28, 28, 1)?  DLPy is expecting 4-D tensors here, and it is getting 2-D tensors.

**Comment by TheodorGosden** [comment]
@eusdougc Now I've finally managed to to make it 4-D instead of 2-d (I find it weird that it can't accept images with 2-D?)

My code is pretty close to the same, the interesting thing is in the bottom. I don't know why, but when I first started using `input_weights_file` and  `load_weights_from_keras` it wanted to get the files from the CAS server dir, but now it uses the local os dir? I should maybe mention, this is the first time I've really coded in python, i'm from the JS and R world.



from __future__ import print_function

import keras
from keras.datasets import mnist
from keras.models import Sequential
from keras.layers import Dense, Dropout, Conv2D, MaxPooling2D, Flatten
from keras.optimizers import RMSprop


batch_size = 128
num_classes = 10
epochs = 1

# the data, shuffled and split between train and test sets
(x_train, y_train), (x_test, y_test) = mnist.load_data()

#x_train = x_train.reshape(60000, 784)
#x_test = x_test.reshape(10000, 784)
x_train = x_train.reshape(60000, 28, 28, 1)
x_test = x_test.reshape(10000,  28, 28, 1)
x_train = x_train.astype('float32')
x_test = x_test.astype('float32')
x_train /= 255
x_test /= 255
print(x_train.shape[0], 'train samples')
print(x_test.shape[0], 'test samples')

# convert class vectors to binary class matrices
y_train = keras.utils.to_categorical(y_train, num_classes)
y_test = keras.utils.to_categorical(y_test, num_classes)


model = Sequential()
#model.add(Dense(512, activation='relu', input_dim=(784)))
model.add(Dense(64, activation='relu', input_shape=(28,28,1)))
model.add(Dropout(0.2))
model.add(Dense(64, activation='relu'))
model.add(Dropout(0.2))
model.add(Flatten())
model.add(Dense(num_classes, activation='softmax'))

model.summary()

model.compile(loss='categorical_crossentropy',
              optimizer=RMSprop(),
              metrics=['accuracy'])

history = model.fit(x_train, y_train,
                    batch_size=batch_size,
                    epochs=epochs,
                    verbose=1,
                    validation_data=(x_test, y_test))
score = model.evaluate(x_test, y_test, verbose=0)
print('Test loss:', score[0])
print('Test accuracy:', score[1])

model.save('my_model_3.h5')

from dlpy import Model
import swat
sess = swat.CAS('rpcger01165.exnet.sas.com', 5570, username='sasdemo', password='Orion123')

####On the CAS Server
model1 = Model.from_keras_model(conn=sess, 
                                keras_model=model,
                                output_model_table='converted_keras_model',
                                include_weights=True,
                                input_weights_file='/media/my_model_2.h5')
##############################################################################
RESPONSE

model1 = Model.from_keras_model(conn=sess, 
                                keras_model=model,
                                output_model_table='converted_keras_model',
                                include_weights=True,
                                input_weights_file='/media/my_model_2.h5')
NOTE: Added action set 'deeplearn'.
NOTE: Model table is attached successfully!
NOTE: Model is named to "converted_keras_model" according to the model name in the table.
Traceback (most recent call last):

  File "<ipython-input-8-953628ed6f56>", line 5, in <module>
    input_weights_file='/media/my_model_2.h5')

  File "C:\Users\sdktgo\AppData\Local\conda\conda\envs\tensorflowkeras2\lib\site-packages\dlpy\model.py", line 289, in from_keras_model
    write_keras_hdf5_from_file(keras_model, input_weights_file, temp_HDF5)

  File "C:\Users\sdktgo\AppData\Local\conda\conda\envs\tensorflowkeras2\lib\site-packages\dlpy\model_conversion\write_keras_model_parm.py", line 47, in write_keras_hdf5_from_file
    f_in = h5py.File(hdf5_in, 'r')

  File "C:\Users\sdktgo\AppData\Local\conda\conda\envs\tensorflowkeras2\lib\site-packages\h5py\_hl\files.py", line 312, in __init__
    fid = make_fid(name, mode, userblock_size, fapl, swmr=swmr)

  File "C:\Users\sdktgo\AppData\Local\conda\conda\envs\tensorflowkeras2\lib\site-packages\h5py\_hl\files.py", line 142, in make_fid
    fid = h5f.open(name, flags, fapl=fapl)

  File "h5py\_objects.pyx", line 54, in h5py._objects.with_phil.wrapper

  File "h5py\_objects.pyx", line 55, in h5py._objects.with_phil.wrapper

  File "h5py\h5f.pyx", line 78, in h5py.h5f.open

OSError: Unable to open file (unable to open file: name = '/media/my_model_2.h5', errno = 2, error message = 'No such file or directory', flags = 0, o_flags = 0)

####Locally
model1 = Model.from_keras_model(conn=sess, 
                                keras_model=model,
                                output_model_table='converted_keras_model',
                                include_weights=True,
                                input_weights_file='C:/Users/sdktgo/my_model_3.h5')
##############################################################################
RESPONSE

model1 = Model.from_keras_model(conn=sess, 
                                keras_model=model,
                                output_model_table='converted_keras_model',
                                include_weights=True,
                                input_weights_file='C:/Users/sdktgo/my_model_3.h5')

NOTE: Model table is attached successfully!
NOTE: Model is named to "converted_keras_model" according to the model name in the table.
Traceback (most recent call last):

  File "<ipython-input-9-ff5e4998f180>", line 5, in <module>
    input_weights_file='C:/Users/sdktgo/my_model_3.h5')

  File "C:\Users\sdktgo\AppData\Local\conda\conda\envs\tensorflowkeras2\lib\site-packages\dlpy\model.py", line 289, in from_keras_model
    write_keras_hdf5_from_file(keras_model, input_weights_file, temp_HDF5)

  File "C:\Users\sdktgo\AppData\Local\conda\conda\envs\tensorflowkeras2\lib\site-packages\dlpy\model_conversion\write_keras_model_parm.py", line 70, in write_keras_hdf5_from_file
    layer_names = [n.decode('utf8') for n in f_in.attrs['layer_names']]

  File "h5py\_objects.pyx", line 54, in h5py._objects.with_phil.wrapper

  File "h5py\_objects.pyx", line 55, in h5py._objects.with_phil.wrapper

  File "C:\Users\sdktgo\AppData\Local\conda\conda\envs\tensorflowkeras2\lib\site-packages\h5py\_hl\attrs.py", line 60, in __getitem__
    attr = h5a.open(self._id, self._e(name))

  File "h5py\_objects.pyx", line 54, in h5py._objects.with_phil.wrapper

  File "h5py\_objects.pyx", line 55, in h5py._objects.with_phil.wrapper

  File "h5py\h5a.pyx", line 77, in h5py.h5a.open

KeyError: "Can't open attribute (can't locate attribute: 'layer_names')"

**Comment by eusdougc** [comment]
@TheodorGosden - images often are manipulated in NHWC (or NCHW) format where

N = number of images
H = height of image (in pixels)
W = width of image (in pixels)
C = number of channels per image

You are working with MNIST data, which is gray-scale data, so 

N = 60000 (for training) or 10000 (for test)
H = 28
W = 28
C = 1

Other image data sets have 3 channels per image (e.g. ImageNet).  In order to handle a wide variety of image data, 4-D tensors are pretty standard.

Some questions:

1) You have the following lines in your code

x_train = x_train.reshape(60000, 28, 28, 1)
x_test = x_test.reshape(10000, 28, 28, 1)

what are the dimensions of x_train and x_test before reshaping?

2) I see this line

model.save('**my_model_3.h5**')

and then this

####On the CAS Server
model1 = Model.from_keras_model(conn=sess,
keras_model=model,
output_model_table='converted_keras_model',
include_weights=True,
input_weights_file='**/media/my_model_2.h5**')

So you are saving to **my_model_3.h5** and trying to read from **/media/my_model_2.h5**?  That shouldn't work unless you have some sort of soft link between the two that you don't describe.

3) For your client side attempt, I am curious as to the contents of C:/Users/sdktgo/my_model_3.h5.  Can you post the file (or send it to me)?  Can you also verify that this is the same file that was written by 

model.save(**my_model_3.h5**)

**Comment by TheodorGosden** [comment]
Thanks for the explanation, I figured it was something along those lines :)

1. If i run the following `x_train.shap` I get `(60000, 28, 28)`. This is before I did the reshape, after i get (60000, 28, 28, 1).

2. I manually moved the files over via MobaXterm. Sorry, for not being clear.

3. I can verify it was the the same file written by `model.save('my_model_3.h5')`. Please find my_model_3.h5 attached (in a zip).
[my_model_3.zip](https://github.com/sassoftware/python-dlpy/files/2620280/my_model_3.zip)

**Comment by eusdougc** [comment]
Thanks for the update.  The reshape shouldn't affect your data then, but I had to ask to be sure.  For question number 2, I don't know whether you caught that you were saving to file my_model_**3** but trying to read my_model_**2**?  Does it work if you read from my_model_**3**?

I will look at the contents of your HDF5 file and see if I can reconcile it with the Python error.

**Comment by TheodorGosden** [comment]
Oh right, sorry. I had a whole arsenal of models in there, both my_model_2 and _3. It produces the same result. 
![image](https://user-images.githubusercontent.com/19152803/49088894-95436300-f25a-11e8-81cd-5836533fcd4d.png)


The question is more why it all of a sudden switch from reading on the server, to reading locally. That's the part I don't get.

Okay, please write if you have any questions, I'll be awaiting your answer.

**Comment by eusdougc** [comment]
This is the documentation for from_keras_model(), it might answer your question regarding client/server reading:

        Generate a model object from a Keras model object

        Parameters
        ----------
        conn : CAS
            The CAS connection object.
        keras_model : keras_model object
            Specifies the keras model to be converted.
        output_model_table : string or dict or CAS table, optional
            Specifies the CAS table to store the deep learning model.
            Default: None
        include_weights : bool, optional
            Specifies whether to load the weights of the keras model.
            Default: True
        input_weights_file : string, optional
            A fully specified **client side path** to the HDF5 file that stores
            the keras model weights. Only effective when include_weights=True.
            If None is given, the current weights in the keras model will be used.
            Default: None

Since this does not show up on the DLPy page, we probably need to open an issue to figure out why.  I will make sure that happens.  Having said that, I'd like to suggest that you try the following in your code.  Delete this line from your script

model.save('my_model_3.h5')

and replace

model1 = Model.from_keras_model(conn=sess,
keras_model=model,
output_model_table='converted_keras_model',
include_weights=True,
input_weights_file='/media/my_model_2.h5')

with

model1 = Model.from_keras_model(conn=sess,
keras_model=model,
output_model_table='converted_keras_model',
include_weights=True)

You are actually doing an unnecessary step in saving the model to an HDF5 file (unless you want this file for some reason).  

The error you are getting indicates that a field in the HDF5 file is missing.  After looking at the file you posted, I see that it is present at a lower level in the tree structure.  I will open an issue to address this.

**Comment by TheodorGosden** [comment]
Hi again @eusdougc 

I've tried to run your code - but the weirdest thing happens. If I just do `include_weights=True` then it still stores my weights in a local file?

`model1 = Model.from_keras_model(conn=sess, 
                                keras_model=model,
                                output_model_table='converted_keras_model',
                                include_weights=True)
NOTE: Added action set 'deeplearn'.
NOTE: Model table is attached successfully!
NOTE: Model is named to "converted_keras_model" according to the model name in the table.
NOTE: the model weights has been stored in the following file:
C:\Users\sdktgo\converted_keras_model_weights.kerasmodel.h5`

I guess that instead of saving the file with DLPy I could just save and load it with Keras, and then import the model with `from_keras_model`

I know this a feature request and not really an issue, but are you planning to make a function so you can register a model you've built? It would make sense to me that you just could push the model to model manager.

**Comment by eusdougc** [comment]
@TheodorGosden - so it sounds like you were able to run your script successfully, you were just surprised by the behavior of the function.  Is that correct?

Let me give you a little background, and then the function behavior might not seem so surprising.  We cannot directly import a Keras model into the SAS deep learning framework.  We have a Viya action that will import the deep learning model parameters (from an HDF5 file), but that is only part of the process.  The function from_keras_model() performs two important steps:

1) it converts the Keras Python model description to an equivalent SAS Python model.  The model that is returned from model1 = Model.from_keras_model() is the SAS Python equivalent of the Keras model.

2) it saves the Keras parameters (weights/biases) to an HDF5 file that can be read by the Viya action that imports deep learning model parameters.  Note that this HDF5 file conforms to the naming convention that is expected by this Viya action.

These two steps are required for any Keras model.  Speaking from experience, manually doing one or both steps is quite tedious/time-consuming/error-prone.  If you provide an HDF5 file as a parameter to from_keras_model(), then you must ensure that the HDF5 file conforms to the naming convention expected by the Viya action.  We need to add a disclaimer to the function documentation to make this clear (e.g. "NOTE: use with caution - your HDF5 file must conform to this naming convention ...).

One you have converted the Keras model and created a SAS-compatible HDF5 file, there is one more step to import the model parameters.  You simply invoke

model1.load_weights_from_file(path='_your_model_path_',fomat_type='KERAS')

Note that the model path must be visible from the CAS server, so you need to either copy the HDF5 file created by from_keras_model() to a place visible by the server, or work in a directory that is visible to both the client and the server.  You can then use your DLPy-equivalent Keras model for further training or inference.

To your question

"I guess that instead of saving the file with DLPy I could just save and load it with Keras, and then import the model with from_keras_model"

Does my explanation address your question?

I don't know what to tell you about your feature request

"I know this a feature request and not really an issue, but are you planning to make a function so you can register a model you've built? It would make sense to me that you just could push the model to model manager."

I think this is beyond the scope of what we planned to do with DLPy, but perhaps others with more knowledge can comment here.

**Comment by ethem-kinginthenorth** [comment]
Cool. From my understanding what we need is to have an example to clarify what @eusdougc explained for future reference. I am closing this issue and opening another one for that example. Thanks.
